version: '3'

services:
  api:
    container_name: onfly_teste
    build: '.'
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    environment:
      NODE_ENV: local
    depends_on:
      - postgres
    ports:
      - '3000:3000'
      - '9229:9229'

  postgres:
    container_name: db_onfly
    image: postgres:11
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_onfly
    ports:
      - '5432:5432'
    volumes:
      - ../postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


networks:
  default:
    external:
      name: teste_onfly
